<a href="https://colab.research.google.com/github/ayush-that/tensorflow/blob/main/00_tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In this notebook, I'm going to cover some of the most fundamental concepts of tensors using TensorFlow.

Topics covered in this notebook -
- Introduction to tensors
- Getting Information from tensors
- Manipulating tensors
- Tensors & NumPy
- Using @tf.function (a way to speed up your regular Python functions)
- Using GPUs with TensorFlow (or TPUs)
- Excercises to practice

In [ ]:
# Import Tensorflow
import tensorflow as tf
print(tf.__version__)

2.17.0


In [ ]:
# Create tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
# Check the number of dimensions of a tensor (ndim stands for number of dimensions)
scalar.ndim

0

In [ ]:
# Create a vector
vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
# Check the dimension of our vector
vector.ndim

1

In [ ]:
# Create a matrix (has more than 1 dimension)
matrix = tf.constant([[10, 7],
                      [7, 10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [ ]:
# Check the dimension of our matrix
matrix.ndim

2

In [ ]:
# Create another matrix
another_matrix = tf.constant([[3.,7.],[2.,5.],[6.,9.]], dtype=tf.float16)
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[3., 7.],
       [2., 5.],
       [6., 9.]], dtype=float16)>

In [ ]:
# What's the number of dimensions of another_matrix
another_matrix.ndim

2

In [ ]:
# Let's create a tensor
tensor = tf.constant([[[3,4,1],
                      [2,4,5]],
                      [[4,5,1],
                       [3,1,2]],
                     [[1,4,2],
                      [5,3,2]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[3, 4, 1],
        [2, 4, 5]],

       [[4, 5, 1],
        [3, 1, 2]],

       [[1, 4, 2],
        [5, 3, 2]]], dtype=int32)>

In [ ]:
# What's the number of dimensions of tensor
tensor.ndim

3

What I've created so far:

1. Scaler: a single number
2. Vector: a number with direction (e.g. wind speed and direction)
3. Matrix: a 2-dimensional array of numbers
4. Tensor: an n-dimensional array of numbers (when n can be any number, a 0-dimensional tensor is a scalar, a 1-dimensional tensor is a vector)

In [ ]:
# Creating tensors with tf.Variable
# Create the same tensor with tf.Variable() as above
changeable_tensor = tf.Variable([10,7])
unchangeable_tensor = tf.constant([10,7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [ ]:
# Let's try to change one of the elements in our changeable tensor
# changeable_tensor[0]
# changeable_tensor[0] = 7

In [ ]:
# How about we try .assign()
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [ ]:
# Let's try change out unchangeable tensor
# unchangeable_tensor[0].assign(7)

🔑 **Note:** Rarely in practive you will need to decide whether to use `tf.constant` or `tf.Variable` to create you. However, if in doubt, use `tf.constant` and change it later if needed.

### Creating Random tensors
Random tensors are tensors of arbitary size which contain random numbers.

In [ ]:
# Create two random (but the same) tensors
random_1 = tf.random.Generator.from_seed(42) # set seed for reproducibility
random_1 = random_1.normal(shape=(3, 2))
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3,2))

# Are they equal?
random_1, random_2, random_1 == random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

In [ ]:
# Shuffle a tensor (valuable for when you want to shuffle your data so the inherant
not_shuffled = tf.constant([[10, 7],
                            [2,7],
                            [7,4]])
shuffled = tf.random.shuffle(not_shuffled)
shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 2,  7],
       [ 7,  4]], dtype=int32)>

🛠️ **Excercise**: Read through TensorFlow documentation on random seed generation.

https://www.tensorflow.org/api_docs/python/tf/random/set_seed and practice writing 5 random tensors and shuffle them.

It looks like if we want out shuffled tensors to be in the same order, we've got to use the global level random seed as well as the operation level random seed:

> Rule 4: "If both the global and the operation seed are set: Both seeds aare used in conjection to determine the random seqiuence."

In [ ]:
tf.random.set_seed(101) # global level random seed
tf.random.shuffle(not_shuffled, seed=101) # operation level random seed

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 7,  4],
       [ 2,  7],
       [10,  7]], dtype=int32)>

### Other ways to make tensors

In [ ]:
tf.ones([3, 4])

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)>

In [ ]:
# Craete a tensor of all zeroes
tf.zeros([3, 3])
tf.zeros(shape=(4, 3))

<tf.Tensor: shape=(4, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

### Turn Numpy arrays into tensors

The main difference between NumPy arrays and TensorFlow tensors is that tensors can be run on a GPU computing.

In [ ]:
# You can also turn NumPy arrays into tensors
import numpy as np

# Create a NumPy array between 1 and 25
numpy_A = np.arange(1, 25, dtype=np.int32)
numpy_A

# x = tf.constant(some_matrix) # capital for matric or tensor
# y = tf.constant(vector) # non-capital for vector

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [ ]:
A = tf.constant(numpy_A, shape=(2, 3, 4)) # 2 * 3 * 4 = 24
B = tf.constant(numpy_A)
A, B

(<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]], dtype=int32)>,
 <tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32)>)

### Getting information from tensors
When dealing with tensors you probably want to be aware of the following attributes:

* Shape
* Size
* Axis or dimension
* Size

In [ ]:
# Craete a rank 4 tensor (4 dimensions)
rank_4_tensor = tf.zeros(shape=[2, 3, 4, 5]) # 2 * 3 * 4 * 5 = 120
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
rank_4_tensor[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [ ]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [ ]:
# Get various attributes of our tensor

print("Datatype of every element:", rank_4_tensor.dtype)
print("Number of dimensions (rank)", rank_4_tensor.ndim)
print("Shape of tensor: ", rank_4_tensor.shape)
print("Elements along the 0-axis:", rank_4_tensor.shape[0])
print("Elements along the last axis:", rank_4_tensor.shape[-1])
print("Total numbers of elements in our tensor:", tf.size(rank_4_tensor))
print("Total number of elements in our tensor:", tf.size(rank_4_tensor).numpy())

Datatype of every element: <dtype: 'float32'>
Number of dimensions (rank) 4
Shape of tensor:  (2, 3, 4, 5)
Elements along the 0-axis: 2
Elements along the last axis: 5
Total numbers of elements in our tensor: tf.Tensor(120, shape=(), dtype=int32)
Total number of elements in our tensor: 120


### Indexing tensors
Tensors can be indexed just like Python lists.

In [ ]:
some_list = [1, 2, 3, 4, 5, 6]
some_list[:2]

[1, 2]

In [ ]:
# Get the first 2 elements of each dimension
rank_4_tensor[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [ ]:
# Get the first element from each dimension from each index except for the final one
rank_4_tensor[:1, :1, :1, :]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
# Crete a rank 2 tensor (2 dimensions)
rank_2_tensor = tf.constant([[1, 4],
                             [2, 4]])
rank_2_tensor.shape, rank_2_tensor.ndim

(TensorShape([2, 2]), 2)

In [ ]:
some_list , some_list[-1]

([1, 2, 3, 4, 5, 6], 6)

In [ ]:
# Get the last item of each of row of our rank 2 tensor
rank_2_tensor[:, -1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([4, 4], dtype=int32)>

In [ ]:
# Add in extra dimension to our rank 2 tensor
rank_3_tensor = rank_2_tensor[..., tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[1],
        [4]],

       [[2],
        [4]]], dtype=int32)>

In [ ]:
# Alternative to tf.newaxis
tf.expand_dims(rank_2_tensor, axis=-1) # -1 means expand the final axis

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[1],
        [4]],

       [[2],
        [4]]], dtype=int32)>

In [ ]:
tf.expand_dims(rank_2_tensor, axis=0) # -1 means expand the zero axis

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[1, 4],
        [2, 4]]], dtype=int32)>

### Manipulating tensors (tensor operations)

**Basic Operations**

+, -, *, /

In [ ]:
# You can add values to a tensor using the addition operator

In [ ]:
tensor = tf.constant([[1,2],
                      [3,4]])
tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[11, 12],
       [13, 14]], dtype=int32)>

In [ ]:
# Original tensor is unchanged
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [ ]:
# Multiplication
tensor * 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10, 20],
       [30, 40]], dtype=int32)>

In [ ]:
# Subtraction
tensor -10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[-9, -8],
       [-7, -6]], dtype=int32)>

In [ ]:
# We can use the tensorflow built-in library
tf.multiply(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10, 20],
       [30, 40]], dtype=int32)>

In [ ]:
# Original tensor is unchanged
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

### Matrix multiplication in tensorflow

In machine learning, matrix multiplication is one of the most comman tensor operations. There are two rules for tensors (or matrices) that need to be satisfied to be able to multiply them:

1. The inner dimensions must match.
2. The resulting matrix has the shape of the inner dimensions.

In [ ]:
# Home work
t1 = tf.constant([[1, 2, 5],
                  [7, 2, 1],
                  [3, 3, 3]])
t2 = tf.constant([[3, 5],
                  [6, 7],
                  [1, 8]])
tf.matmul(t1, t2)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[20, 59],
       [34, 57],
       [30, 60]], dtype=int32)>

In [ ]:
# Matrix multiplication in tensorflow
print(tensor)
tf.matmul(tensor, tensor)

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 7, 10],
       [15, 22]], dtype=int32)>

In [ ]:
tensor, tensor

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4]], dtype=int32)>)

In [ ]:
# Matrix multiplication with Python operator "@"
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 7, 10],
       [15, 22]], dtype=int32)>

In [ ]:
# Create a (3, 2) tensor
x1 = tf.constant([[1, 2],
                  [3, 6],
                  [5, 7]])

# Create another (3, 2) tensor
x2 = tf.constant([[2, 4],
                  [5, 6],
                  [4,9]])

x1, x2

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 6],
        [5, 7]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[2, 4],
        [5, 6],
        [4, 9]], dtype=int32)>)

In [ ]:
# We will not reshape x1 so that we can multiply it
tf.reshape(x1, (2, 3)) @ x2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 24,  43],
       [ 65, 117]], dtype=int32)>

In [ ]:
# Now reshaping them using transpose
tf.transpose(x1) @ x2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 37,  67],
       [ 62, 107]], dtype=int32)>

### Dot Product

Matrix multiplication is also referred to as the dot product. We can perform it using the following functions:

1. tf.matmul()
2. tf.tensordot()

Generally when performing matrix multiplication on two tensors and one of the axes doesn't line up, you transpose them to make them satisfy the rules.

In [ ]:
x2 = tf.transpose(x2)
x1, x2

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 6],
        [5, 7]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[2, 5, 4],
        [4, 6, 9]], dtype=int32)>)

In [ ]:
# Perform the dot product on X and Y (requires X or Y to be transposed)
tf.tensordot(x1, x2, axes = 1)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[10, 17, 22],
       [30, 51, 66],
       [38, 67, 83]], dtype=int32)>

In [ ]:
# Dot product using x1 and x2 transposed
tf.transpose(x1) @ tf.transpose(x2) # Transpose x1 so the inner dimensions match

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 37,  67],
       [ 62, 107]], dtype=int32)>

In [ ]:
# Dot product using x1 and x2 (reshaped)
x1 @ tf.reshape(x2, (2, 3))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[10, 17, 22],
       [30, 51, 66],
       [38, 67, 83]], dtype=int32)>

In [ ]:
# Check values of x2 and transposed x2
print("Normal x2: \n", x2)
print("Transposed x2: \n", tf.transpose(x2))
print("Reshaped x2: \n", tf.reshape(x2, (2, 3)))

Normal x2: 
 tf.Tensor(
[[2 5 4]
 [4 6 9]], shape=(2, 3), dtype=int32)
Transposed x2: 
 tf.Tensor(
[[2 4]
 [5 6]
 [4 9]], shape=(3, 2), dtype=int32)
Reshaped x2: 
 tf.Tensor(
[[2 5 4]
 [4 6 9]], shape=(2, 3), dtype=int32)


### Changing the data types of a tensor

In [ ]:
# Checking TensorFlow version
tf.__version__

'2.17.0'

In [ ]:
# Create a new tensor with default datatype i.e. float32
B = tf.constant([1.6, 4.2])
B.dtype

tf.float32

In [ ]:
C = tf.constant([1, 2])
C.dtype

tf.int32

In [ ]:
# Cast into a 16-bit type
B = tf.cast(B, dtype = tf.float16)
B.dtype

tf.float16

### Aggregating Tensors

Aggregating tensors is condensing them from multiple values down to a smaller amount of values